parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        schema_filter: ~^(?!lock_keys|view_)~
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.6.11'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                replace: Oro\ORM\Query\AST\Functions\String\Replace
            numeric_functions:
                to_number: App\Utils\ToNumber
                rand: App\Doctrine\Rand
            datetime_functions:
                utc_timestamp: App\Utils\UtcTimestamp
