# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true

    access_denied_listener:
        json: true

    exception:
        enabled: true
        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
        codes:
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': 401
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
        messages:
            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true
            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

    view:
        view_response_listener:  true

    service:
        serializer: fos_rest.serializer.symfony

    serializer:
        groups: ['API']

    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, js ] }
            - { path: ^/, prefer_extension: true, fallback_format: html, priorities: [ html, '*/*' ] }
