fos_oauth_server:
    db_driver: orm       # Drivers available: orm, mongodb, or propel
    client_class:        App\Entity\Api\Client
    access_token_class:  App\Entity\Api\AccessToken
    refresh_token_class: App\Entity\Api\RefreshToken
    auth_code_class:     App\Entity\Api\AuthCode
    service:
            user_provider: fos_user.user_provider.username
