fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true
            template: bundles/FOSUserBundle/Registration/email.html.twig
    from_email:
        address: "%env(MAILER_USER)%"
        sender_name: "%env(MAILER_USER)%"
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: App\Manager\UserManagerInterface