fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    change_password:
        form:
            type: App\Form\ChangePasswordType
    registration:
        form:
            type: App\Form\RegistrationType
        confirmation:
            enabled: true
            template: bundles/FOSUserBundle/Registration/email.html.twig
    resetting:
        form:
            type: App\Form\ResettingType
        email:
            template: bundles/FOSUserBundle/Resetting/email.html.twig
        token_ttl: 7200
    from_email:
        address: "%env(MAILER_USER)%"
        sender_name: "%env(MAILER_USER)%"
    service:
        mailer: fos_user.mailer.twig_swift
        user_manager: App\Manager\UserManagerInterface
    group:
        group_class: Sonata\UserBundle\Entity\BaseGroup
