nelmio_security:
    clickjacking:
        paths:
            '^/(?!.*/embeded$).*': DENY
        content_types: []
    csp:
        hosts: []
        content_types: []
        enforce:
            report-uri: '%router.request_context.base_url%/csp-report'
            default-src:
                - 'self'
            object-src:
                - 'none'
            script-src:
                - 'strict-dynamic'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https:'
                - 'http:'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://fonts.googleapis.com'
                - 'https://cdn.jsdelivr.net/emojione/2.2.7/assets/css/emojione.min.css'
                - 'https://*.tawk.to'
            connect-src:
                - 'self'
                - 'wss://api.mintme.com/'
                - 'wss://api.mintme.abchosting.org/'
                - 'https://*.facebook.net'
                - 'https://*.facebook.com'
                - 'https://connect.facebook.net'
                - 'https://www.facebook.com'
                - 'https://www.google-analytics.com'
                - 'https://*.doubleclick.net'
                - 'https://*.mintme.com'
                - 'https://mintme.com'
                - 'https://*.tawk.to'
                - 'wss://*.tawk.to'
                - '%env(MERCURE_PUBLISH_URL)%'
            img-src:
                - 'data:'
                - '*'
            font-src:
                - 'self'
                - 'https://fonts.gstatic.com'
                - 'https://static-v.tawk.to'
                - 'https://embed.tawk.to'
            frame-src:
                - 'https://www.facebook.com'
                - 'https://accounts.google.com'
                - 'https://content.googleapis.com'
                - 'https://va.tawk.to'
                - 'https://www.youtube.com'
                - 'https://www.google.com'
                - 'https://*.coinify.com'
                - 'https://platform.twitter.com'
                - 'https://content-youtube.googleapis.com'
            base-uri:
                - 'self'
            worker-src:
                - 'none'
            manifest-src:
                - 'self'
            media-src:
                - '*'
        report_endpoint:
            log_level: 'error' # Use the appropriate log_level
            log_channel: 'security'      # Declare the channel to use with the logger
            filters:
                # Filter false positive reports given a domain list
                domains: true
                # Filter false positive reports given a scheme list
                schemes: true
                # Filter false positive reports given known browser bugs
                browser_bugs: true
                # Filter false positive reports given known injected scripts
                injected_scripts: true
                # You can add you custom filter rules by implementing Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\NoiseDetectorInterface
                # and tag the service with "nelmio_security.csp_report_filter"
            dismiss:
                # A list of key-values that should be dismissed
                # A key is either a domain or a regular expression
                # A value is a source or an array of source. The '*' wilcard is accepted
                '/^data:/': 'script-src'
                '/^https?:\/\/\d+\.\d+\.\d+\.\d+(:\d+)*/': '*'
                'maxcdn.bootstrapcdn.com': '*'
                'www.gstatic.com': ['media-src', 'img-src']
    forced_ssl:
        hsts_max_age: 31536000 # 30 days
        hsts_subdomains: true
        hsts_preload: true

