nelmio_security:
    csp:
        hosts: []
        content_types: []
        enforce:
            default-src:
                - 'self'
            object-src:
                - 'none'
            script-src:
                - 'strict-dynamic'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https:'
                - 'http:'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://*.googleapis.com'
                - 'https://cdn.jsdelivr.net/emojione/2.2.7/assets/css/emojione.min.css'
                - 'https://*.tawk.to'
            connect-src:
                - 'self'
                - 'wss://self'
                - 'https://*.google-analytics.com'
                - 'https://*.mintme.com'
                - 'https://mintme.com'
                - 'https://static-v.tawk.to'
                - 'https://va.tawk.to'
                - 'https://*.tawk.to'
                - 'wss://*.tawk.to'
            img-src:
                - '*'
                - 'data:'
            font-src:
                - 'self'
                - 'https://*.gstatic.com'
                - 'https://*.tawk.to'
            frame-src:
                - 'https://*.facebook.com'
                - 'https://*.google.com'
                - 'https://*.googleapis.com'
                - 'https://*.tawk.to'
                - 'https://*.youtube.com'
            base-uri:
                - 'self'
            worker-src:
                - 'none'
            manifest-src:
                - 'self'
            media-src:
                - '*'
