nelmio_security:
    csp:
        hosts: []
        content_types: []
        enforce:
            report-uri: '%router.request_context.base_url%/csp-report'
            default-src:
                - 'self'
            object-src:
                - 'none'
            script-src:
                - 'strict-dynamic'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https:'
                - 'http:'
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://*.googleapis.com'
                - 'https://cdn.jsdelivr.net/emojione/2.2.7/assets/css/emojione.min.css'
                - 'https://*.tawk.to'
            connect-src:
                - 'self'
                - 'wss://self'
                - 'https://*.google-analytics.com'
                - 'https://*.mintme.com'
                - 'https://mintme.com'
                - 'https://static-v.tawk.to'
                - 'https://va.tawk.to'
                - 'https://*.tawk.to'
                - 'wss://*.tawk.to'
            img-src:
                - '*'
                - 'data:'
            font-src:
                - 'self'
                - 'https://*.gstatic.com'
                - 'https://*.tawk.to'
            frame-src:
                - 'https://*.facebook.com'
                - 'https://*.google.com'
                - 'https://*.googleapis.com'
                - 'https://*.tawk.to'
                - 'https://*.youtube.com'
            base-uri:
                - 'self'
            worker-src:
                - 'none'
            manifest-src:
                - 'self'
            media-src:
                - '*'
        report_endpoint:
            log_level: 'error' # Use the appropriate log_level
            log_channel: 'security'      # Declare the channel to use with the logger
            filters:
                # Filter false positive reports given a domain list
                domains: true
                # Filter false positive reports given a scheme list
                schemes: true
                # Filter false positive reports given known browser bugs
                browser_bugs: true
                # Filter false positive reports given known injected scripts
                injected_scripts: true
                # You can add you custom filter rules by implementing Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\NoiseDetectorInterface
                # and tag the service with "nelmio_security.csp_report_filter"
            dismiss:
                # A list of key-values that should be dismissed
                # A key is either a domain or a regular expression
                # A value is a source or an array of source. The '*' wilcard is accepted
                '/^data:/': 'script-src'
                '/^https?:\/\/\d+\.\d+\.\d+\.\d+(:\d+)*/': '*'
                'maxcdn.bootstrapcdn.com': '*'
                'www.gstatic.com': ['media-src', 'img-src']
