nelmio_security:
    csp:
        hosts: []
        content_types: []
        enforce:
            default-src:
                - 'self'
            object-src:
                - 'none'
            script-src:
                - 'strict-dynamic'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https:'
                - 'http:'
            style-src:
                - 'self'
                - '*.googleapis.com'
                - '*.jsdelivr.net'
                - '*.tawk.to'
                - 'unsafe-inline'
            connect-src:
                - 'self'
                - '*.google-analytics.com'
                - '*.tawk.to'
                - 'wss://*.tawk.to'
            img-src:
                - 'self'
                - 'data:'
                - '*.google-analytics.com'
            font-src:
                - 'self'
                - '*.gstatic.com'
            frame-src:
                - '*.facebook.com'
                - '*.tawk.to'
                - '*.youtube.com'
