old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    producers:
        payment:
            connection:       default
            class:            App\Producer\PaymentProducer
        payment_retry:
            connection:       default
            class:            App\Producer\RetryPaymentProducer
