old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    consumers:
        payment:
            connection: default
            queue_options:    {name: 'payment-callback', durable: false}
            callback: payment_consumer
        deposit:
            connection: default
            queue_options:    {name: 'deposit', durable: true}
            callback: deposit_consumer
        deploy:
            connection: default
            queue_options:    {name: 'deploy', durable: true}
            callback: deploy_consumer
        contract_update:
            connection: default
            queue_options:    {name: 'contract-update', durable: true}
            callback: contract_update_consumer
        market:
            connection: default
            exchange_options: {name: 'market', type: 'x-delayed-message', durable: true, arguments: {x-delayed-type: ['S', fanout]}}
            queue_options:    {name: 'market', durable: true}
            callback: market_consumer

    producers:
        payment:
            connection: default
            class: App\Producer\PaymentProducer
        payment_retry:
            connection: default
            class: App\Producer\RetryPaymentProducer
        market_delayed:
            connection: default
            exchange_options: {name: 'market', type: 'x-delayed-message', durable: true, arguments: {x-delayed-type: ['S', fanout]}}
            class: App\Producer\MarketDelayedProducer
