old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'

    consumers:
        payment:
            connection: default
            queue_options: {name: 'payment-callback', durable: false}
            callback: payment_consumer
        deposit:
            connection: default
            queue_options: {name: 'deposit', durable: true}
            callback: deposit_consumer
        market:
            connection: default
            exchange_options: {name: 'market', type: fanout}
            queue_options:    {name: 'market', durable: true}
            callback: market_consumer

    producers:
        payment:
            connection: default
            class: App\Producer\PaymentProducer
        payment_retry:
            connection: default
            class: App\Producer\RetryPaymentProducer
        market:
            connection: default
            exchange_options: {name: 'market', type: fanout}
        market_delayed:
            connection: default
            exchange_options: {name: 'market_delayed', type: fanout, durable: true}
            class: App\Producer\MarketDelayedProducer
