sonata_admin:
    title: 'mintme'
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            reciprocal.links:
                label: reciprocal links
                items:
                    - admin.reciprocal.links
            knowledge.base:
                label: Knowledge Base
                items:
                    - admin.knowledgebase
                    - admin.knowledgebase.category
                    - admin.knowledgebase.subcategory

            blacklist:
                label: Blacklist
                items:
                    - admin.blacklist

            usergroup:
                label: Users Administration
                items:
                    - admin.user

            sonata.admin.group.content:
                label: News
                items:
                    - sonata.news.admin.post
                    - sonata.news.admin.comment

            sonata.admin.group.media:
                label: Resources
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery

            sonata.admin.group.classification:
                label: Classification
                items:
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

    templates:
        layout: admin/custom_layout.html.twig
        edit: admin/custom_edit.html.twig
        base_list_field: admin/custom_base_list_field.html.twig

    assets:
        extra_javascripts:
            - bundles/fosckeditor/ckeditor.js
            - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
            - bundles/sonataformatter/markitup/sets/markdown/set.js
            - bundles/sonataformatter/markitup/sets/html/set.js
            - bundles/sonataformatter/markitup/sets/textile/set.js

        extra_stylesheets:
            - bundles/sonataformatter/markitup/skins/sonata/style.css
            - bundles/sonataformatter/markitup/sets/markdown/style.css
            - bundles/sonataformatter/markitup/sets/html/style.css
            - bundles/sonataformatter/markitup/sets/textile/style.css
