sonata_admin:
    title: 'mintme'
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

        groups:
            knowledge.base:
                label: Knowledge Base
                items:
                    - admin.knowledgebase
                    - admin.knowledgebase.category
                    - admin.knowledgebase.subcategory

            blacklist:
                label: Blacklist
                items:
                    - admin.blacklist

            usergroup:
                label: Users Administration
                items:
                    - admin.user

            sonata.admin.group.content:
                label: News
                items:
                    - sonata.news.admin.post
                    - sonata.news.admin.comment

            sonata.admin.group.media:
                label: Resources
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery

            sonata.admin.group.classification:
                label: Classification
                items:
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

    templates:
        layout: admin/custom_layout.html.twig
        edit: admin/custom_edit.html.twig
        base_list_field: admin/custom_base_list_field.html.twig
