monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!cron', '!rabbitmq', '!payments', '!exchange']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        cron:
            type: stream
            path: "%kernel.logs_dir%/cron.log"
            level: info
            channels: ['cron']
        rabbitmq:
            type: stream
            path: "%kernel.logs_dir%/rabbitmq.log"
            level: debug
            channels: ['rabbitmq']
        payments:
            type: stream
            path: "%kernel.logs_dir%/payments.log"
            level: debug
            channels: ['payments']
        exchange:
            type: stream
            path: "%kernel.logs_dir%/exchange.log"
            level: debug
            channels: ['exchange']
