monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", '!cron', '!rabbitmq']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        cron:
            type: stream
            path: "%kernel.logs_dir%/cron.log"
            level: debug
            channels: ['cron']
        rabbitmq:
            type: stream
            path: "%kernel.logs_dir%/rabbitmq.log"
            level: debug
            channels: ['rabbitmq']
