App\Form\Model\EmailModel:
    properties:
        email:
            - NotBlank: ~
            - Email:
                message: 'Invalid email address.'
            - App\Validator\Constraints\UserEmail: ~
