parameters:
    service: 'mintme'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    locale: 'en'
    sonata.media.admin.media.class: App\Admin\MediaAdmin

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,*/Model}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    coinmarketcap.rest_rpc:
        class: App\Communications\GuzzleRestWrapper
        arguments:
            $url: '%coinbase_api_url%'
            $timeoutSeconds: '%coinbase_api_timeout%'
            $headers:
                Accept: application/json

    viabtc.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%env(VIABTC_RPC)%'
            $timeoutSeconds: '%viabtc_response_timeout_seconds%'
            $auth: '%viabtc_auth%'

    deposit.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%env(DEPOSIT_RPC)%'
            $timeoutSeconds: '%deposit_response_timeout_seconds%'
            $auth: '%deposit_auth%'

    withdraw.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%env(WITHDRAW_RPC)%'
            $timeoutSeconds: '%withdraw_response_timeout_seconds%'
            $auth: '%withdraw_auth%'

    App\Communications\CoinmarketcapCommunicator:
        arguments:
            $rpc: '@coinmarketcap.rest_rpc'

    App\Wallet\Deposit\DepositGatewayCommunicator:
        arguments:
            $jsonRpc: '@deposit.json_rpc'

    App\Exchange\Trade\Config\LimitOrderConfig:
        arguments:
            $takerFeeRate: '%taker_fee_rate%'
            $makerFeeRate: '%maker_fee_rate%'

    App\Exchange\Trade\TraderFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Exchange\Market\MarketFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Wallet\Withdraw\Fetcher\Storage\WithdrawStorage:
        arguments:
            $jsonRpc: '@withdraw.json_rpc'
            $service: '%service%'

    App\Exchange\Balance\BalanceFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Communications\Factory\RpcClientFactoryInterface: '@App\Communications\Factory\GuzzleRpcClientFactory'

    App\Manager\TwoFactorManagerInterface: '@App\Manager\TwoFactorManager'

    App\Wallet\Withdraw\Communicator\AMQPCommunicator:
        arguments:
            $paymentProducer: '@old_sound_rabbit_mq.payment_producer'
            $paymentRetryProducer: '@old_sound_rabbit_mq.payment_retry_producer'
            $service: '%service%'

    App\Communications\AMQP\MarketProducer:
        arguments:
            $producer: '@old_sound_rabbit_mq.market_delayed_producer'

    FOS\UserBundle\Form\Factory\FormFactory:
        arguments:
            $formFactory: '@form.factory'
            $name: '%fos_user.profile.form.name%'
            $type: '%fos_user.profile.form.type%'
            $validationGroups: '%fos_user.profile.form.validation_groups%'

    App\Utils\Verify\WebsiteVerifier:
        arguments:
            $timeoutSeconds: '%verify_timeout_seconds%'

    App\Command\UpdateTokenRelease:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: cron }

    App\Command\UpdatePendingWithdrawals:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: cron }

    # SonataAdminBundle Registered Admin Classes
    # =======================================
    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            - null
            - App\Entity\User
            - App\Controller\UserAdminCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true
        calls:
             - [init, ['@fos_user.user_manager', '@App\Manager\ProfileManagerInterface']]

    admin.blacklist:
        class: App\Admin\BlacklistAdmin
        arguments:
            - null
            - App\Entity\Blacklist
            - Sonata\AdminBundle\Controller\CRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: Blacklist }
        public: true

    admin.reciprocal.links:
        class: App\Admin\ReciprocalLinksAdmin
        arguments:
            - null
            - App\Entity\ReciprocalLinks
            - Sonata\AdminBundle\Controller\CRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: Reciprocal Links }
        public: true

    admin.knowledgebase:
        class: App\Admin\KnowledgeBase\KnowledgeBaseAdmin
        arguments:
            - null
            - App\Entity\KnowledgeBase\KnowledgeBase
            - Sonata\AdminBundle\Controller\CRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: Knowledge Base }
        public: true

    admin.knowledgebase.category:
        class: App\Admin\KnowledgeBase\KnowledgeBaseCategoryAdmin
        arguments:
            - null
            - App\Entity\KnowledgeBase\Category
            - Sonata\AdminBundle\Controller\CRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: KB Categories }
        public: true

    admin.knowledgebase.subcategory:
        class: App\Admin\KnowledgeBase\KnowledgeBaseSubcategoryAdmin
        arguments:
            - null
            - App\Entity\KnowledgeBase\Subcategory
            - Sonata\AdminBundle\Controller\CRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: KB Subcategories }
        public: true

    # Required by rabbitmq bundle
    market_consumer:
        class: 'App\Consumers\MarketConsumer'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    payment_consumer:
        class: 'App\Consumers\PaymentConsumer'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    deposit_consumer:
        class: 'App\Consumers\DepositConsumer'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    wallet:
        class: 'App\Wallet\Wallet'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: payments }

    trader:
        class: 'App\Exchange\Trade\Trader'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: exchange }

    balancer:
        class: 'App\Exchange\Balance\BalanceHandler'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: exchange }

    App\Manager\UserManager:
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
            - "@doctrine.orm.entity_manager"
            - "%fos_user.model.user.class%"

    App\Exchange\Trade\Config\PrelaunchConfig:
        arguments:
            - "%prelaunch_finish_datetime%"
            - "%referral_fee%"
            - "%prelaunch_autostart%"

    App\Security\PrelaunchVoter:
        arguments:
            $env: "%kernel.environment%"

    App\Security\HackerVoter:
        arguments:
            $isHackerAllowed: "%is_hacker_allowed%"

    app.mailer:
        class: App\Mailer\Mailer
        arguments:
            $mail: "%env(MAILER_USER)%"

    App\Mailer\MailerInterface: "@app.mailer"

    App\Exchange\Balance\Factory\BalanceViewFactory:
        arguments:
            $tokenSubunit: "%token_precision%"

    App\Serializer\TradableNormalizer:
        arguments:
            $tokenSubunit: "%token_precision%"

    App\Controller\ResettingController:
        decorates: fos_user.resetting.controller
        public: true
        arguments:
            - '@event_dispatcher'
            - '@fos_user.resetting.form.factory'
            - '@fos_user.user_manager'
            - '@fos_user.util.token_generator'
            - '@fos_user.mailer'
            - '%fos_user.resetting.retry_ttl%'

    App\Controller\RegistrationController:
        decorates: fos_user.registration.controller
        public: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $formFactory: '@fos_user.registration.form.factory'
            $userManager: '@fos_user.user_manager'
            $tokenStorage: '@security.token_storage'

    App\Exchange\Config\Config:
        arguments:
            $offset: "%env(VIABTC_OFFSET)%"

    App\Controller\API\WebSocketAPIController:
        arguments:
            $isAuth: "%env(VIABTC_FORCE_WS_AUTH)%"

    App\EventSubscriber\KernelSubscriber:
        arguments:
            $isAuth: "%env(VIABTC_FORCE_WS_AUTH)%"

    App\EventListener\BruteForceListener:
        arguments:
            $session: '@session'
            $secret: '%env(APP_SECRET)%'
        tags:
            - { name: kernel.event_listener, event: scheb_two_factor.authentication.attempt }
            - { name: kernel.event_listener, event: scheb_two_factor.authentication.failure }
            - { name: kernel.event_listener, event: scheb_two_factor.authentication.success }

    App\EventListener\RegistrationInitializedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize }

    App\EventListener\RegistrationCompletedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed }

    kernel.listener.command_dispatch:
        class: App\EventListener\ConsoleCommandsListener
        tags:
            - { name: kernel.event_listener, event: console.terminate }

    FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer'

    App\Logger\UserActionProcessor:
        autowire: true
        tags:
            - { name: monolog.processor, channel: user_action }

    monolog.formatter.user_action:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "%%datetime%%|%%level_name%%|%%extra.ip_address%%|%%extra.username%%|%%message%%|%%context%%\n"
            - "Y-m-d H:i:s"

    App\Logger\UserActionLogger:
        autowire: true
        tags:
            - { name: monolog.logger, channel: user_action }

    logout_listner:
        class: App\EventListener\LogoutListener

    App\EventListener\ChangePasswordListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.change_password.edit.completed }

    App\EventSubscriber\SitemapSubscriber:
        arguments:
            - "@router"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    App\Controller\API\TokensAPIController:
        arguments:
            $expirationTime: "%token_deletion_confirm_code_expiration_time%"

    two_factor.auth_require_handler:
        class: App\Security\TwoFactorRequireHandler
        public: true
