parameters:
    locale: 'en'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    viabtc.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%viabtc_rpc%'
            $timeoutSeconds: '%viabtc_response_timeout_seconds%'

    withdraw.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%withdraw_rpc%'
            $timeoutSeconds: '%withdraw_response_timeout_seconds%'

    App\Exchange\Trade\Config\LimitOrderConfig:
        arguments:
            $takerFeeRate: '%taker_fee_rate%'
            $makerFeeRate: '%maker_fee_rate%'

    App\Exchange\Trade\Trader:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Exchange\Market\MarketFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Withdraw\Fetcher\Storage\WithdrawStorage:
        arguments:
            $jsonRpc: '@withdraw.json_rpc'
            $service: '%service%'

    App\Exchange\Balance\BalanceFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Communications\Factory\RpcClientFactoryInterface: '@App\Communications\Factory\GuzzleRpcClientFactory'

    App\EventListener\RegistrationInitializedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize }

    App\Manager\TwoFactorManagerInterface: '@App\Manager\TwoFactorManager'

    App\Manager\TokenManager: ~
    App\Manager\TokenManagerInterface: '@App\Manager\TokenManager'

    App\Fetcher\ProfileFetcher: ~
    App\Fetcher\ProfileFetcherInterface: '@App\Fetcher\ProfileFetcher'

    App\Utils\MailerDispatcher:
        arguments:
            $mailer: '@fos_user.mailer.default'

    App\Withdraw\Communicator\AMQPCommunicator:
        arguments:
            $paymentProducer: '@old_sound_rabbit_mq.payment_producer'
            $paymentRetryProducer: '@old_sound_rabbit_mq.payment_retry_producer'
            $service: '%service%'
            $fee: '%withdraw_fee%'

    FOS\UserBundle\Form\Factory\FormFactory:
        arguments:
            $formFactory: '@form.factory'
            $name: '%fos_user.profile.form.name%'
            $type: '%fos_user.profile.form.type%'
            $validationGroups: '%fos_user.profile.form.validation_groups%'

    App\Verify\WebsiteVerifier:
        arguments:
            $timeoutSeconds: '%verify_timeout_seconds%'

    App\Verify\WebsiteVerifierInterface: '@App\Verify\WebsiteVerifier'

    App\Command\UpdateTokenRelease:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: cron }

    App\Serializer\BalanceResultContainerNormalizer:
        tags: ['serializer.normalizer']