parameters:
    service: 'mintme'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    locale: 'en'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,*/Model}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    viabtc.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%viabtc_rpc%'
            $timeoutSeconds: '%viabtc_response_timeout_seconds%'
    
    deposit.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%deposit_rpc%'
            $timeoutSeconds: '%deposit_response_timeout_seconds%'

    withdraw.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%withdraw_rpc%'
            $timeoutSeconds: '%withdraw_response_timeout_seconds%'

    App\Exchange\Trade\Config\LimitOrderConfig:
        arguments:
            $takerFeeRate: '%taker_fee_rate%'
            $makerFeeRate: '%maker_fee_rate%'

    App\Exchange\Trade\Trader:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Exchange\Market\MarketFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Withdraw\Fetcher\Storage\WithdrawStorage:
        arguments:
            $jsonRpc: '@withdraw.json_rpc'
            $service: '%service%'

    App\Exchange\Balance\BalanceFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Deposit\DepositGatewayCommunicator:
        arguments:
            $jsonRpc: '@deposit.json_rpc'

    App\Communications\Factory\RpcClientFactoryInterface: '@App\Communications\Factory\GuzzleRpcClientFactory'

    App\EventListener\RegistrationInitializedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize }

    App\Manager\TwoFactorManagerInterface: '@App\Manager\TwoFactorManager'

    App\Manager\TokenManager: ~
    App\Manager\TokenManagerInterface: '@App\Manager\TokenManager'

    App\Fetcher\ProfileFetcher: ~
    App\Fetcher\ProfileFetcherInterface: '@App\Fetcher\ProfileFetcher'

    App\Utils\MailerDispatcher:
        arguments:
            $mailer: '@fos_user.mailer.default'

    App\Withdraw\Communicator\AMQPCommunicator:
        arguments:
            $paymentProducer: '@old_sound_rabbit_mq.payment_producer'
            $paymentRetryProducer: '@old_sound_rabbit_mq.payment_retry_producer'
            $service: '%service%'

    FOS\UserBundle\Form\Factory\FormFactory:
        arguments:
            $formFactory: '@form.factory'
            $name: '%fos_user.profile.form.name%'
            $type: '%fos_user.profile.form.type%'
            $validationGroups: '%fos_user.profile.form.validation_groups%'

    App\Verify\WebsiteVerifier:
        arguments:
            $timeoutSeconds: '%verify_timeout_seconds%'

    App\Verify\WebsiteVerifierInterface: '@App\Verify\WebsiteVerifier'

    App\Command\UpdateTokenRelease:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: cron }

    App\Consumers\PaymentConsumer:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }
    
    App\Consumers\DepositConsumer:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    App\Serializer\BalanceResultContainerNormalizer:
        tags: ['serializer.normalizer']


    # SonataAdminBundle Registered Admin Classes
    # =======================================
    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            - null
            - App\Entity\User
            - App\Controller\UserAdminCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true
        calls:
             - [init, ['@fos_user.user_manager', '@App\Manager\ProfileManagerInterface']]

    payment_consumer: '@App\Consumers\PaymentConsumer'
    
    deposit_consumer: '@App\Consumers\DepositConsumer'

    App\Manager\UserManager:
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
            - "@doctrine.orm.entity_manager"
            - "%fos_user.model.user.class%"

    App\EventListener\RegistrationCompletedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed }

    App\Exchange\Trade\Config\PrelaunchConfig:
        arguments:
            - "%prelaunch_finish_datetime%"
            - "%prelaunch_referral_trading_period%"
            - "%prelaunch_referral_fee%"

    App\Security\PrelaunchVoter:
        arguments:
            $env: "%kernel.environment%"