parameters:
    service: 'mintme'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    locale: 'en'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,*/Model}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    viabtc.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%viabtc_rpc%'
            $timeoutSeconds: '%viabtc_response_timeout_seconds%'

    deposit.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%deposit_rpc%'
            $timeoutSeconds: '%deposit_response_timeout_seconds%'

    withdraw.json_rpc:
        class: App\Communications\GuzzleWrapper
        arguments:
            $url: '%withdraw_rpc%'
            $timeoutSeconds: '%withdraw_response_timeout_seconds%'

    App\Wallet\Deposit\DepositGatewayCommunicator:
        arguments:
            $jsonRpc: '@deposit.json_rpc'

    App\Exchange\Trade\Config\LimitOrderConfig:
        arguments:
            $takerFeeRate: '%taker_fee_rate%'
            $makerFeeRate: '%maker_fee_rate%'

    App\Exchange\Trade\TraderFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Exchange\Market\MarketFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Wallet\Withdraw\Fetcher\Storage\WithdrawStorage:
        arguments:
            $jsonRpc: '@withdraw.json_rpc'
            $service: '%service%'

    App\Exchange\Balance\BalanceFetcher:
        arguments:
            $jsonRpc: '@viabtc.json_rpc'

    App\Communications\Factory\RpcClientFactoryInterface: '@App\Communications\Factory\GuzzleRpcClientFactory'

    App\Manager\TwoFactorManagerInterface: '@App\Manager\TwoFactorManager'

    App\Wallet\Withdraw\Communicator\AMQPCommunicator:
        arguments:
            $paymentProducer: '@old_sound_rabbit_mq.payment_producer'
            $paymentRetryProducer: '@old_sound_rabbit_mq.payment_retry_producer'
            $service: '%service%'

    FOS\UserBundle\Form\Factory\FormFactory:
        arguments:
            $formFactory: '@form.factory'
            $name: '%fos_user.profile.form.name%'
            $type: '%fos_user.profile.form.type%'
            $validationGroups: '%fos_user.profile.form.validation_groups%'

    App\Utils\Verify\WebsiteVerifier:
        arguments:
            $timeoutSeconds: '%verify_timeout_seconds%'

    App\Command\UpdateTokenRelease:
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: cron }

    # SonataAdminBundle Registered Admin Classes
    # =======================================
    admin.user:
        class: App\Admin\UserAdmin
        arguments:
            - null
            - App\Entity\User
            - App\Controller\UserAdminCRUDController
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true
        calls:
             - [init, ['@fos_user.user_manager', '@App\Manager\ProfileManagerInterface']]

    # Required by rabbitmq bundle
    payment_consumer:
        class: 'App\Consumers\PaymentConsumer'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    deposit_consumer:
        class: 'App\Consumers\DepositConsumer'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: rabbitmq }

    wallet:
        class: 'App\Wallet\Wallet'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: payments }

    trader:
        class: 'App\Exchange\Trade\Trader'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: exchange }

    balancer:
        class: 'App\Exchange\Balance\BalanceHandler'
        arguments:
            $logger: '@logger'
        tags:
            - { name: monolog.logger, channel: exchange }

    App\Manager\UserManager:
        arguments:
            - "@fos_user.util.password_updater"
            - "@fos_user.util.canonical_fields_updater"
            - "@doctrine.orm.entity_manager"
            - "%fos_user.model.user.class%"

    App\Exchange\Trade\Config\PrelaunchConfig:
        arguments:
            - "%prelaunch_finish_datetime%"
            - "%prelaunch_referral_trading_period%"
            - "%prelaunch_referral_fee%"
            - "%prelaunch_autostart%"

    App\Security\PrelaunchVoter:
        arguments:
            $env: "%kernel.environment%"

    App\Security\HackerVoter:
        arguments:
            $isHackerAllowed: "%is_hacker_allowed%"

    App\Mailer\Mailer:
        arguments:
            $mail: "%env(MAILER_USER)%"

    App\Exchange\Balance\Factory\BalanceViewFactory:
        arguments:
            $tokenSubunit: "%token_precision%"

    App\Serializer\TradableNormalizer:
        arguments:
            $tokenSubunit: "%token_precision%"

    App\Controller\ResettingController:
        decorates: fos_user.resetting.controller
        public: true
        arguments:
            - '@event_dispatcher'
            - '@fos_user.resetting.form.factory'
            - '@fos_user.user_manager'
            - '@fos_user.util.token_generator'
            - '@fos_user.mailer'
            - '%fos_user.resetting.retry_ttl%'

    App\Exchange\Config\Config:
        arguments:
            $offset: "%env(VIABTC_OFFSET)%"

    App\Controller\API\WebSocketAPIController:
        arguments:
            $isAuth: "%env(VIABTC_FORCE_WS_AUTH)%"

    App\EventSubscriber\KernelSubscriber:
        arguments:
            $isAuth: "%env(VIABTC_FORCE_WS_AUTH)%"

    App\EventListener\RegistrationInitializedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize }

    App\EventListener\RegistrationCompletedListener:
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.completed }

    FOS\UserBundle\Mailer\MailerInterface: '@fos_user.mailer'
