<?php declare(strict_types = 1);

namespace App\Tests\Utils;

use App\Utils\Converter\TokenNameNormalizerInterface;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class TokenNameNormalizerTest extends TestCase
{
    /** @var TokenNameNormalizerInterface */
    private $tokenNameNormalizer;

    public function setUp(): void
    {
        $this->tokenNameNormalizer = $this->createMock(TokenNameNormalizerInterface::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * @dataProvider parserProvider
     */
    public function testParser(string $name, string $parsedName): void
    {
        $this->assertEquals($parsedName, $this->tokenNameNormalizer->parse($name));
    }

    public function parserProvider(): array
    {
        return [
            ['test', 'test'],
            [' test', 'test'],
            ['test  123', 'test 123'],
            ['test--123', 'test-123'],
            [' - - - t--e st', 't-e st'],
            [' te s  t ', 'te s t'],
            [' test--', 'test'],
            [' test-1--  1', 'test-1-1'],
            ['- tes t-1--  1', 'tes t-1-1'],
        ];
    }


    /**
     * @dataProvider dasherProvider
     */
    public function testDasher(string $name, string $parsedName): void
    {
        $this->assertEquals($parsedName, $this->tokenNameNormalizer->dashed($name));
    }

    public function dasherProvider(): array
    {
        return [
            ['test', 'test'],
            ['test 123', 'test-123'],
            ['test--123', 'test-123'],
            [' test', 'test'],
            [' test ', 'test'],
            [' test--', 'test'],
            [' test-1--  1', 'test-1-1'],
            ['- tes t-1--  1', 'tes-t-1-1'],
        ];
    }
}
